# Generated by Django 4.2 on 2023-05-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_category',
            name='category_id',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbl_category',
            name='description',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='tbl_category',
            name='photo',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='tbl_shope',
            name='photo',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='tbl_shope',
            name='shope_id',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
