# Generated by Django 4.2 on 2023-05-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0002_alter_tbl_category_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='shopeid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
