# Generated by Django 4.2 on 2023-05-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0004_idgen_productid_tbl_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='shope_id',
            field=models.ForeignKey(default='Shope1', on_delete=django.db.models.deletion.CASCADE, to='Grace.tbl_shope'),
            preserve_default=False,
        ),
    ]
