# Generated by Django 4.2 on 2023-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0005_tbl_product_shope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='coustomerid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
