# Generated by Django 4.2 on 2023-05-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0006_idgen_coustomerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_coustomer',
            fields=[
                ('coustomer_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('coustomer_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_coustomer',
            },
        ),
    ]
