# Generated by Django 4.2 on 2023-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0008_tbl_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_shope',
            name='username',
            field=models.CharField(default='Kola@2000', max_length=200),
            preserve_default=False,
        ),
    ]
