# Generated by Django 4.2 on 2023-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0009_tbl_shope_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_coustomer',
            name='username',
            field=models.CharField(default='Amal@2000', max_length=200),
            preserve_default=False,
        ),
    ]
