# Generated by Django 4.2 on 2023-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0010_tbl_coustomer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_coustomer',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tbl_shope',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
