# Generated by Django 4.2 on 2023-05-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0011_alter_tbl_coustomer_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('review_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=225)),
                ('review_date', models.CharField(max_length=200)),
                ('coustomer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grace.tbl_coustomer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grace.tbl_product')),
            ],
            options={
                'db_table': 'tbl_review',
            },
        ),
    ]
