# Generated by Django 4.2 on 2023-05-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0012_tbl_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='reviewid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
