# Generated by Django 4.2 on 2023-05-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0013_idgen_reviewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='orderid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
