# Generated by Django 4.2 on 2023-05-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0015_tbl_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='order_adress',
            field=models.CharField(default='o', max_length=200),
            preserve_default=False,
        ),
    ]
