# Generated by Django 4.2 on 2023-05-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0016_tbl_order_order_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_order',
            old_name='order_adress',
            new_name='delivery_adress',
        ),
    ]
