# Generated by Django 4.2 on 2023-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0017_rename_order_adress_tbl_order_delivery_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryagent',
            fields=[
                ('agent_id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_deliveryagent',
            },
        ),
    ]
