# Generated by Django 4.2 on 2023-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0018_tbl_deliveryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='idgen',
            name='agentid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
