# Generated by Django 4.2 on 2023-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0020_tbl_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_login',
            name='hint',
            field=models.CharField(default='grace', max_length=200),
            preserve_default=False,
        ),
    ]
